import Head from 'next/head'
import axios from 'axios'
import NFTList from '../components/FactList'
import {
  Box,
  Button,
  ButtonGroup,
  CSSReset,
  Heading,
  Icon,
  Link,
  ChakraProvider,
  FormControl,
  FormLabel,
  FormErrorMessage,
  Input,
  Checkbox,
  Progress,
  Radio,
  RadioGroup,
  Stack,
  Textarea
} from '@chakra-ui/react'
import { extendTheme } from '@chakra-ui/react'
import FactList from '../components/FactList'
const colors = {
  brand: {
    // 900: '#1a365d',
    // 800: '#153e75',
    // 700: '#2a69ac',
  },
}
const theme = extendTheme({ colors });

function Home({ catFactsData, status }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
        <CSSReset />
        <Box w={500} p={4} m="20px auto">
          <Heading as="h1" size="xl" textAlign="center" m={5}>
            Chakra Example h1
          </Heading>
          <Box as="p" textAlign="center">
            Example using Nextjs and{' '}
            <Link href="https://chakra-ui.com" isExternal>
              Chakra <Icon name="external-link" mx="2px" />
            </Link>
          </Box>
          <FactList factsData={catFactsData} status={status}></FactList>
        </Box>
      </ChakraProvider>
    </>
  )
}

export async function getServerSideProps(context) {
  let catFactsData = null;
  let status = { "isOk": false, "error": null };
  try {
    const response = await axios.get('https://catfact.ninaja/facts');
    let catFacts = response.data;
    catFactsData = catFacts.data;
    status.isOk = true;
    return { props: { catFactsData, status } }
  } catch (error) {
    status.error = error.response?.data ?? { "code": null, "message": "No message" };
    console.log(`status ${JSON.stringify(status)}`)
    return { props: { catFactsData, status } }
  }
}

export default Home